// GenerateHeaders.py AUTOGENERATED FILE--DO NOT EDIT!
#pragma once
namespace th11 {
    // Stripped down add_pointer
    template <typename T>
    struct add_pointer {
        using type = T*; 
    };
    template <typename T> struct add_pointer<T&> { using type = T*; };
    template <typename T>
    using add_pointer_t = typename add_pointer<T>::type;
}

#define g_anmManager (*reinterpret_cast<th11::add_pointer_t<AnmManager*>>(0x4c3268))
#define g_supervisor (*reinterpret_cast<th11::add_pointer_t<Supervisor>>(0x4c3280))
#define g_renderQuad144 (*reinterpret_cast<th11::add_pointer_t<RenderVertex144[4]>>(0x4c91d8))
#define g_chain (*reinterpret_cast<th11::add_pointer_t<Chain*>>(0x4c3234))
#define g_window (*reinterpret_cast<th11::add_pointer_t<Window>>(0x4c3d88))
#define g_pbgArchive (*reinterpret_cast<th11::add_pointer_t<PbgArchive>>(0x4c9680))
#define g_pbgArchives (*reinterpret_cast<th11::add_pointer_t<PbgArchive*>>(0x4c3c48))
#define g_numEntriesInDatFile (*reinterpret_cast<th11::add_pointer_t<int>>(0x4a8ed0))
#define g_lzssDict (*reinterpret_cast<th11::add_pointer_t<byte[0x2001]>>(0x4c0ee8))
#define g_lzssTree (*reinterpret_cast<th11::add_pointer_t<LzssTreeNode[0x2001]>>(0x4a8ed8))
#define g_fpsCounter (*reinterpret_cast<th11::add_pointer_t<FpsCounter*>>(0x4a8d80))
#define g_spellcard (*reinterpret_cast<th11::add_pointer_t<Spellcard*>>(0x4a8d6c))
#define g_squareVertices (*reinterpret_cast<th11::add_pointer_t<RenderVertexSq[4]>>(0x4c9248))
#define g_gameSpeed (*reinterpret_cast<th11::add_pointer_t<float>>(0x4a7948))
#define g_globals (*reinterpret_cast<th11::add_pointer_t<Globals>>(0x4a56e0))
#define g_player (*reinterpret_cast<th11::add_pointer_t<Player*>>(0x4a8eb4))
#define g_soundManager (*reinterpret_cast<th11::add_pointer_t<SoundManager>>(0x4c3e80))
#define g_soundConfigTable (*reinterpret_cast<th11::add_pointer_t<SoundConfig[56]>>(0x4a34f0))
#define g_anmRngContext (*reinterpret_cast<th11::add_pointer_t<RngContext>>(0x4c2ef8))
#define g_replayRngContext (*reinterpret_cast<th11::add_pointer_t<RngContext>>(0x4c2f00))
#define g_app (*reinterpret_cast<th11::add_pointer_t<HANDLE>>(0x4c9898))
#define g_gdiObject_0 (*reinterpret_cast<th11::add_pointer_t<HFONT>>(0x4c2eec))
#define g_gdiObject_2 (*reinterpret_cast<th11::add_pointer_t<HFONT>>(0x4c0ee4))
#define g_gdiObject_1 (*reinterpret_cast<th11::add_pointer_t<HFONT>>(0x4c2ee8))
#define g_gdiObject_3 (*reinterpret_cast<th11::add_pointer_t<HFONT>>(0x4a8ed4))
#define g_joyAxisX_Min (*reinterpret_cast<th11::add_pointer_t<int>>(0x4c2f2c))
#define g_joyAxisX_Max (*reinterpret_cast<th11::add_pointer_t<int>>(0x4c2f30))
#define g_joyAxisY_Min (*reinterpret_cast<th11::add_pointer_t<int>>(0x4c2f34))
#define g_joyAxisY_Max (*reinterpret_cast<th11::add_pointer_t<int>>(0x4c2f38))
#define g_defaultGameConfig (*reinterpret_cast<th11::add_pointer_t<GameConfig>>(0x4c93d8))
#define g_inputManager (*reinterpret_cast<th11::add_pointer_t<InputManager>>(0x4c92a8))
#define g_laserDataVftable (*reinterpret_cast<th11::add_pointer_t<LaserBaseVftable>>(0x494a0c))
#define g_laserManager (*reinterpret_cast<th11::add_pointer_t<LaserManager*>>(0x4a8e94))
#define g_itemManager (*reinterpret_cast<th11::add_pointer_t<ItemManager*>>(0x4a8e90))
#define g_currentEclFilePath (*reinterpret_cast<th11::add_pointer_t<char[256]>>(0x4c9928))
#define g_enemyManager (*reinterpret_cast<th11::add_pointer_t<EnemyManager*>>(0x4a8d7c))
#define g_bomb (*reinterpret_cast<th11::add_pointer_t<Bomb*>>(0x4a8d64))
#define g_shotFile (*reinterpret_cast<th11::add_pointer_t<ShotFile*>>(0x4c3240))
#define g_lockedTexPitch (*reinterpret_cast<th11::add_pointer_t<uint32_t>>(0x4a58d0))
#define g_lockedTexBits (*reinterpret_cast<th11::add_pointer_t<void*>>(0x4a58e0))
#define g_lockedTexFormat (*reinterpret_cast<th11::add_pointer_t<D3DFORMAT>>(0x4a58c0))
#define g_softwareCanvas (*reinterpret_cast<th11::add_pointer_t<HDC>>(0x4a58d4))
#define g_lockedTexBufferSize (*reinterpret_cast<th11::add_pointer_t<int>>(0x4a58cc))
#define g_ShooterOnInitCallbacks (*reinterpret_cast<th11::add_pointer_t<void**>>(0x4a3a28))
#define g_ShooterOnTickCallbacks (*reinterpret_cast<th11::add_pointer_t<void**>>(0x4a3a3c))
#define g_ShooterOnDrawCallbacks (*reinterpret_cast<th11::add_pointer_t<void**>>(0x4c3244))
#define g_ShooterOnHitCallbacks (*reinterpret_cast<th11::add_pointer_t<void**>>(0x4c3248))
#define g_optionFormationOffsets (*reinterpret_cast<th11::add_pointer_t<int[6][16]>>(0x4a7ac8))
#define g_joyCaps (*reinterpret_cast<th11::add_pointer_t<JOYCAPSA>>(0x4c2f08))
#define g_bulletManager (*reinterpret_cast<th11::add_pointer_t<BulletManager*>>(0x4a8d68))
#define g_gui (*reinterpret_cast<th11::add_pointer_t<Gui*>>(0x4a8d84))
#define g_loadingThread (*reinterpret_cast<th11::add_pointer_t<Thread>>(0x4a58e4))
